import images from './images.json';
export type Property = {id:string;slug:string;title:string;address:string;zone:string;type:'Casa'|'Quinta'|'Terreno';operation:'Venta'|'Alquiler';currency:'USD'|'ARS';price:number;covered:number|null;land:number|null;beds:number|null;baths:number|null;features:string[];services:string[];description:string;note?:string;featured:boolean;source:string;images:string[]};
const source='https://www.inmuebles.clarin.com/';
const covers:Record<string,number>={'20172379':16,'19671035':4,'19103957':1,'19904982':1,'20324632':3,'19101685':4};
const photo=(id:keyof typeof images)=>[images[id][covers[id]-1],...images[id].filter((_,i)=>i!==covers[id]-1)];
export const verified='6 de septiembre de 2026';
export const properties:Property[]=[
{id:'20172379',slug:'casa-camino-al-dique',title:'Un parque para vivirlo todos los días',address:'Arturo Illia 3613',zone:'Camino al Dique',type:'Casa',operation:'Venta',currency:'USD',price:139000,covered:158,land:1922,beds:3,baths:2,features:['Pileta','Apto crédito','Parque','Cochera','Asador'],services:['Agua corriente','Electricidad','Gas natural','Internet'],description:'Una casa rodeada de verde sobre Camino al Dique. Sus 158 m² cubiertos reúnen tres dormitorios, dos baños, living y comedor independientes, y cocina equipada. Las aberturas de madera y los ambientes amplios acompañan una construcción tradicional. Afuera, el parque de 1.922 m², la pileta de 3 × 5 metros, el asador y la cochera semicubierta invitan a disfrutar del entorno.',featured:true,source:source+'casa-en-venta-en-cruz-del-eje-4-ambientes--20172379',images:photo('20172379')},
{id:'19671035',slug:'casa-pileta-domingo-mathieu',title:'Espacio para compartir, adentro y afuera',address:'Domingo Mathieu casi Alem',zone:'Cruz del Eje',type:'Casa',operation:'Venta',currency:'USD',price:107000,covered:200,land:357,beds:4,baths:2,features:['Pileta','Apto crédito','Permuta','Cochera','Asador','Terraza'],services:['Agua corriente','Electricidad','Gas natural','Cloacas','Internet'],description:'Una vivienda de dos plantas con cuatro dormitorios, dos baños y living comedor con cocina integrada. El hogar a leña y la escalera de madera dan carácter al interior. Cuenta con garaje, terraza y una galería con asador y horno; el patio incorpora una pileta. La publicación contempla propuestas y la posibilidad de permuta, a evaluar personalmente.',featured:true,source:source+'casa-en-venta-en-cruz-del-eje-5-ambientes--19671035',images:photo('19671035')},
{id:'19103957',slug:'quinta-pellegrini',title:'Más naturaleza, a tu propio ritmo',address:'Pellegrini s/n',zone:'Cruz del Eje',type:'Quinta',operation:'Venta',currency:'USD',price:115000,covered:220,land:70000,beds:3,baths:2,features:['Pileta','Parque','Cochera','Galería'],services:['Agua corriente'],description:'Una quinta con arboleda, frutales y espacios abiertos. La descripción publicada informa siete hectáreas y una vivienda de 220 m² con tres dormitorios, dos baños, living separado, cocina comedor, lavadero y depósito. Se suman galería, pileta y cancha de fútbol. El aviso actual describe cercanía al río Cruz del Eje; el acceso y los límites deben verificarse durante la visita.',note:'El encabezado publica USD 115.000 y la descripción USD 116.000. Las 7 ha provienen de la descripción; el campo de terreno del portal muestra 220 m². Confirmar precio, mensura y límites con el asesor. No se afirma acceso propio al río.',featured:true,source:source+'quinta-en-venta-en-cruz-del-eje-4-ambientes--19103957',images:photo('19103957')},
{id:'19904982',slug:'casa-local-sarmiento',title:'Tu casa y un nuevo proyecto, juntos',address:'Sarmiento al 1900',zone:'Cruz del Eje',type:'Casa',operation:'Venta',currency:'USD',price:55000,covered:130,land:260,beds:3,baths:2,features:['Local comercial','Permuta','Cochera','Patio'],services:['Agua corriente','Electricidad','Gas natural','Internet'],description:'Vivienda con local al frente, a metros de la plaza 25 de Mayo. La casa dispone de tres dormitorios, cocina separada, living comedor, baño, patio e ingreso para dos vehículos. El local comercial se publica con aproximadamente 35 m². El aviso contempla recibir un vehículo como parte de pago, sujeto a evaluación.',note:'Medidas publicadas con diferencias: terreno de 260 m² en el texto y 264 m² en la ficha; cubierta de 120/130 m² en el texto y 130 m² en la ficha. Se muestran 260 y 130 m² orientativos. La ficha informa 2 baños; la descripción detalla uno en la vivienda. Verificar el conjunto.',featured:false,source:source+'casa-en-venta-en-cruz-del-eje-4-ambientes--19904982',images:photo('19904982')},
{id:'20324632',slug:'alquiler-sarmiento-1963',title:'Un nuevo comienzo cerca de todo',address:'Sarmiento 1963',zone:'Cruz del Eje',type:'Casa',operation:'Alquiler',currency:'ARS',price:599000,covered:130,land:null,beds:3,baths:1,features:['Patio','Cochera','Remodelada'],services:['Agua corriente','Gas envasado'],description:'Casa remodelada cerca de la plaza 25 de Mayo. Cuenta con living comedor, cocina semiseparada, lavadero independiente y tres dormitorios de amplias dimensiones. Un baño completo, entrada para vehículos y patio al fondo completan la vivienda. Los requisitos, ajustes, gastos y condiciones se confirman directamente con el asesor.',note:'El encabezado y parte de la descripción publican $599.000; otro apartado del mismo aviso indica $600.000 mensuales. Confirmar valor y condiciones vigentes antes de reservar.',featured:false,source:source+'casa-en-alquiler-en-cruz-del-eje-4-ambientes--20324632',images:photo('20324632')},
{id:'19101685',slug:'terreno-laprida',title:'El espacio donde empieza tu proyecto',address:'Calle Laprida',zone:'Cruz del Eje',type:'Terreno',operation:'Venta',currency:'USD',price:27000,covered:null,land:2500,beds:null,baths:null,features:['Arboleda','Terreno plano'],services:['Agua corriente','Electricidad','Gas natural'],description:'Terreno de aproximadamente 2.500 m² sobre calle Laprida, a una cuadra y media de la Municipalidad y junto a la Escuela José Ingenieros, según el aviso. Su escala permite explorar distintas ideas de uso como interpretación comercial. Cualquier desarrollo depende de verificar normativa, factibilidad de servicios y documentación.',note:'El aviso indica “para escriturar”. Confirmar situación documental y factibilidad urbanística. No se garantiza superficie edificable ni aprobación de un desarrollo.',featured:false,source:source+'terreno-en-venta-en-cruz-del-eje--19101685',images:photo('19101685')}
];
export const money=(p:Property)=>`${p.currency==='USD'?'USD':'$'} ${p.price.toLocaleString('es-AR')}${p.operation==='Alquiler'?' / mes':''}`;
export const area=(v:number|null)=>v===null?'A confirmar':`${v.toLocaleString('es-AR')} m²`;
export const asset=(path:string)=>import.meta.env.BASE_URL+path;
export const wa=(message:string)=>`https://wa.me/5493549555998?text=${encodeURIComponent(message)}`;
export const propertyMessage=(p:Property,visit=false)=>`Hola Gaspar, vi la propiedad ubicada en ${p.address}, Cruz del Eje, publicada a ${money(p)} (ref. ${p.id}) y quisiera ${visit?'confirmar su disponibilidad y agendar una visita.':'saber si continúa disponible y coordinar una visita.'}`;
export const intents={comprar:'Hola Gaspar, estoy buscando una propiedad para comprar en Cruz del Eje. Quisiera conversar sobre las opciones.',alquilar:'Hola Gaspar, busco una propiedad para alquilar en Cruz del Eje. ¿Qué opciones y condiciones están vigentes?',tasar:'Hola Gaspar, quisiera solicitar una tasación de mi propiedad en la zona de Cruz del Eje.',ofrecer:'Hola Gaspar, tengo una propiedad en la zona de Cruz del Eje y quisiera conversar para ofrecerla en venta o alquiler.',permuta:'Hola Gaspar, quisiera consultar por propiedades que acepten permuta y conocer cómo se evalúa una propuesta.',visita:'Hola Gaspar, quisiera coordinar una visita a una propiedad en Cruz del Eje. ¿Podemos conversar?'};
